/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.*;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ALLCH
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Consultas
     */
    
    Controlador objControlador;    
    private static Consultas objConsultas;
    
    public Consultas(Controlador objControlador) {
        
        this.objControlador = objControlador;
        initComponents();
        this.setLocationRelativeTo(null);//Posiona la ventana en el centro
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/Iconos/logoSencillo2000.png")).getImage());
        
        TablaRender renderer = new TablaRender();
        asignarTitulo();
        tablaConsultas.setDefaultRenderer(Object.class, renderer);
        tablaConsultas.setDefaultRenderer(Object.class, renderer);
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Iconos/logoLune.ico"));
        return retValue;
    }
    //Patron Singleton
    public  static Consultas obtenerConsultas(Controlador objControlador){
        
        if(objConsultas == null){
            
            objConsultas = new Consultas(objControlador);            
        }
        return objConsultas;
    }

    public Consultas() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CheckExistencias = new javax.swing.JCheckBox();
        txExistenciasConsultar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConsultas = new javax.swing.JTable();
        labelTotalDineroInventario = new javax.swing.JLabel();
        checkTotalDinero = new javax.swing.JCheckBox();
        checkTotalGanancia = new javax.swing.JCheckBox();
        labelTotalGanancia = new javax.swing.JLabel();
        checkTotalProductos = new javax.swing.JCheckBox();
        labelTotalProductos = new javax.swing.JLabel();
        btnPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("Consultas");

        CheckExistencias.setBackground(new java.awt.Color(255, 255, 255));
        CheckExistencias.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        CheckExistencias.setText("Productos con cantidades menores  a:");
        CheckExistencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckExistenciasMouseClicked(evt);
            }
        });
        CheckExistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckExistenciasActionPerformed(evt);
            }
        });

        txExistenciasConsultar.setBackground(new java.awt.Color(255, 255, 255));
        txExistenciasConsultar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txExistenciasConsultar.setToolTipText("Ingrese el numero a consultar");

        tablaConsultas.setBackground(new java.awt.Color(255, 255, 255));
        tablaConsultas.setForeground(new java.awt.Color(0, 0, 0));
        tablaConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaConsultas.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tablaConsultas.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tablaConsultas);

        labelTotalDineroInventario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        checkTotalDinero.setBackground(new java.awt.Color(255, 255, 255));
        checkTotalDinero.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        checkTotalDinero.setText("Total Dinero Inventario");
        checkTotalDinero.setToolTipText("Calcula un aproximado del total del dinero invertido");
        checkTotalDinero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkTotalDineroMouseClicked(evt);
            }
        });
        checkTotalDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTotalDineroActionPerformed(evt);
            }
        });

        checkTotalGanancia.setBackground(new java.awt.Color(255, 255, 255));
        checkTotalGanancia.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        checkTotalGanancia.setText("Ganancias totales de la Mercancía");
        checkTotalGanancia.setToolTipText("Calcula un total  de la ganancia de las ventas");
        checkTotalGanancia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkTotalGananciaMouseClicked(evt);
            }
        });

        labelTotalGanancia.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        checkTotalProductos.setBackground(new java.awt.Color(255, 255, 255));
        checkTotalProductos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        checkTotalProductos.setText("Cantidad total de productos");
        checkTotalProductos.setToolTipText("Obtiene el total de productos del inventario");
        checkTotalProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkTotalProductosMouseClicked(evt);
            }
        });

        labelTotalProductos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btnPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        btnPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        btnPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Iconos/iconoHogar.png"))); // NOI18N
        btnPrincipal.setText("Principal");
        btnPrincipal.setToolTipText("Vuelve al Menu Principal");
        btnPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(checkTotalProductos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CheckExistencias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkTotalDinero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkTotalGanancia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(labelTotalGanancia, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(labelTotalDineroInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelTotalProductos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txExistenciasConsultar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckExistencias)
                    .addComponent(txExistenciasConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkTotalProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTotalProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkTotalDinero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTotalDineroInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkTotalGanancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTotalGanancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckExistenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckExistenciasMouseClicked
        enviarDatosConsulta();
    }//GEN-LAST:event_CheckExistenciasMouseClicked

    private void btnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalActionPerformed

        if (objControlador.getTipoEmpleadoSesionAbierta().equalsIgnoreCase("usuario")) {

            VistaMenuUsuarioComun interfaz2 = new VistaMenuUsuarioComun(objControlador);
            interfaz2.show();
            this.dispose();
        } else if (objControlador.getTipoEmpleadoSesionAbierta().equalsIgnoreCase("admin")) {
            frontEnd interfaz = new frontEnd(objControlador);
            interfaz.show();
            this.dispose(); // instruccion que cierra la ventana actual
        } else {
            JOptionPane.showMessageDialog(null, "Imposible regresar al Menu Principal \n en este momento");

        }
    }//GEN-LAST:event_btnPrincipalActionPerformed

    private void CheckExistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckExistenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckExistenciasActionPerformed

    private void checkTotalDineroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkTotalDineroMouseClicked
        totalDineroInventario();
    }//GEN-LAST:event_checkTotalDineroMouseClicked

    private void checkTotalDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTotalDineroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkTotalDineroActionPerformed

    private void checkTotalGananciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkTotalGananciaMouseClicked
        gananciaMercancia();
    }//GEN-LAST:event_checkTotalGananciaMouseClicked

    private void checkTotalProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkTotalProductosMouseClicked
        totalProductos();
    }//GEN-LAST:event_checkTotalProductosMouseClicked

    public void enviarDatosConsulta(){
        
        int existencias ;
        if(CheckExistencias.isSelected()){
            
            if(txExistenciasConsultar.getText().equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(null, "Ingrese un valor para buscar");
                
            }else{
                existencias = Integer.parseInt(txExistenciasConsultar.getText());
                objControlador.consultas(existencias, tablaConsultas);
            }                
        }
    }
    
    public void totalDineroInventario(){
        
       
        if(checkTotalDinero.isSelected()){            
            
            objControlador.tota/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.*;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ALLCH
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Consultas
     */
    
    Controlador objControlador;    
    private static Consultas objConsultas;
    
    public Consultas(Controlador objControlador) {
        
        this.objControlador = objControlador;
        initComponents();
        this.setLocationRelativeTo(null);//Posiona la ventana en el centro
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/Iconos/logoSencillo2000.png")).getImage());
        
        TablaRender renderer = new TablaRender();
        asignarTitulo();
        tablaConsultas.setDefaultRenderer(Object.class, renderer);
        tablaConsultas.setDefaultRenderer(Object.class, renderer);
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Iconos/logoLune.ico"));
        return retValue;
    }
    //Patron Singleton
    public  static Consultas obtenerConsultas(Controlador objControlador){
        
        if(objConsultas == null){
            
            objConsultas = new Consultas(objControlador);            
        }
        return objConsultas;
    }

    public Consultas() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CheckExistencias = new javax.swing.JCheckBox();
        txExistenciasConsultar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConsultas = new javax.swing.JTable();
        labelTotalDineroInventario = new javax.swing.JLabel();
        checkTotalDinero = new javax.swing.JCheckBox();
        checkTotalGanancia = new javax.swing.JCheckBox();
        labelTotalGanancia = new javax.swing.JLabel();
        checkTotalProductos = new javax.swing.JCheckBox();
        labelTotalProductos = new javax.swing.JLabel();
        btnPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("Consultas");

        CheckExistencias.setBackground(new java.awt.Color(255, 255, 255));
        CheckExistencias.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        CheckExistencias.setText("Productos con cantidades menores  a:");
        CheckExistencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckExistenciasMouseClicked(evt);
            }
        });
        CheckExistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckExistenciasActionPerformed(evt);
            }
        });

        txExistenciasConsultar.setBackground(new java.awt.Color(255, 255, 255));
        txExistenciasConsultar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txExistenciasConsultar.setToolTipText("Ingrese el numero a consultar");

        tablaConsultas.setBackground(new java.awt.Color(255, 255, 255));
        tablaConsultas.setForeground(new java.awt.Color(0, 0, 0));
        tablaConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaConsultas.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tablaConsultas.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tablaConsultas);

        labelTotalDineroInventario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        checkTotalDinero.setBackground(new java.awt.Color(255, 255, 255));
        checkTotalDinero.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        checkTotalDinero.setText("Total Dinero Inventario");
        checkTotalDinero.setToolTipText("Calcula un aproximado del total del dinero invertido");
        checkTotalDinero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkTotalDineroMouseClicked(evt);
            }
        });
        checkTotalDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTotalDineroActionPerformed(evt);
            }
        });

        checkTotalGanancia.setBackground(new java.awt.Color(255, 255, 255));
        checkTotalGanancia.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        checkTotalGanancia.setText("Ganancias totales de la Mercancía");
        checkTotalGanancia.setToolTipText("Calcula un total  de la ganancia de las ventas");
        checkTotalGanancia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkTotalGananciaMouseClicked(evt);
            }
        });

        labelTotalGanancia.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        checkTotalProductos.setBackground(new java.awt.Color(255, 255, 255));
        checkTotalProductos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        checkTotalProductos.setText("Cantidad total de productos");
        checkTotalProductos.setToolTipText("Obtiene el total de productos del inventario");
        checkTotalProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkTotalProductosMouseClicked(evt);
            }
        });

        labelTotalProductos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btnPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        btnPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        btnPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Iconos/iconoHogar.png"))); // NOI18N
        btnPrincipal.setText("Principal");
        btnPrincipal.setToolTipText("Vuelve al Menu Principal");
        btnPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(checkTotalProductos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CheckExistencias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkTotalDinero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkTotalGanancia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(labelTotalGanancia, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(labelTotalDineroInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelTotalProductos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txExistenciasConsultar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckExistencias)
                    .addComponent(txExistenciasConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkTotalProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTotalProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkTotalDinero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTotalDineroInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkTotalGanancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTotalGanancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckExistenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckExistenciasMouseClicked
        enviarDatosConsulta();
    }//GEN-LAST:event_CheckExistenciasMouseClicked

    private void btnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalActionPerformed

        if (objControlador.getTipoEmpleadoSesionAbierta().equalsIgnoreCase("usuario")) {

            VistaMenuUsuarioComun interfaz2 = new VistaMenuUsuarioComun(objControlador);
            interfaz2.show();
            this.dispose();
        } else if (objControlador.getTipoEmpleadoSesionAbierta().equalsIgnoreCase("admin")) {
            frontEnd interfaz = new frontEnd(objControlador);
            interfaz.show();
            this.dispose(); // instruccion que cierra la ventana actual
        } else {
            JOptionPane.showMessageDialog(null, "Imposible regresar al Menu Principal \n en este momento");

        }
    }//GEN-LAST:event_btnPrincipalActionPerformed

    private void CheckExistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckExistenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckExistenciasActionPerformed

    private void checkTotalDineroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkTotalDineroMouseClicked
        totalDineroInventario();
    }//GEN-LAST:event_checkTotalDineroMouseClicked

    private void checkTotalDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTotalDineroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkTotalDineroActionPerformed

    private void checkTotalGananciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkTotalGananciaMouseClicked
        gananciaMercancia();
    }//GEN-LAST:event_checkTotalGananciaMouseClicked

    private void checkTotalProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkTotalProductosMouseClicked
        totalProductos();
    }//GEN-LAST:event_checkTotalProductosMouseClicked

    public void enviarDatosConsulta(){
        
        int existencias ;
        if(CheckExistencias.isSelected()){
            
            if(txExistenciasConsultar.getText().equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(null, "Ingrese un valor para buscar");
                
            }else{
                existencias = Integer.parseInt(txExistenciasConsultar.getText());
                objControlador.consultas(existencias, tablaConsultas);
            }                
        }
    }
    
    public void totalDineroInventario(){
        
       
        if(checkTotalDinero.isSelected()){            
            
            objControlador.totalDineroInventario(labelTotalDineroInventario);
        }
        
    }    
    
    public void gananciaMercancia(){
        
       
        if(checkTotalGanancia.isSelected()){           
            
            objControlador.ganancia(labelTotalGanancia);
        }
        
    }
    
    public void totalProductos(){
        
        
        if(checkTotalProductos.isSelected()){           
            
            objControlador.totalProductos(labelTotalProductos);
        }
        
    }
    
    private void asignarTitulo() {
        
        setTitle(objControlador.empleadoSesionAbierta());
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckExistencias;
    private javax.swing.JButton btnPrincipal;
    private javax.swing.JCheckBox checkTotalDinero;
    private javax.swing.JCheckBox checkTotalGanancia;
    private javax.swing.JCheckBox checkTotalProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTotalDineroInventario;
    private javax.swing.JLabel labelTotalGanancia;
    private javax.swing.JLabel labelTotalProductos;
    private javax.swing.JTable tablaConsultas;
    private javax.swing.JTextField txExistenciasConsultar;
    // End of variables declaration//GEN-END:variables
}
